# Generated by Django 5.2.4 on 2025-07-14 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='suspendido_hasta',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
