# Generated by Django 5.2.4 on 2025-07-14 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil_user', '0002_perfil_suspendido_hasta'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='suspension',
            field=models.BooleanField(default=False),
        ),
    ]
