# Generated by Django 5.2.4 on 2025-07-14 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil_user', '0003_perfil_suspension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='imagen',
            field=models.ImageField(blank=True, default='images/default-image-jpg', upload_to='perfiles/'),
        ),
    ]
