# Generated by Django 5.2.4 on 2025-07-14 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil_user', '0005_alter_perfil_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='imagen',
            field=models.ImageField(blank=True, default='images/default-user.jpg', upload_to='perfiles/'),
        ),
    ]
