# Generated by Django 5.2.4 on 2025-07-12 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('campus', models.CharField(choices=[('rancagua', 'Campus Rancagua'), ('colchagua', 'Campus Colchagua')], max_length=20)),
                ('contacto', models.CharField(max_length=60)),
                ('categoria', models.CharField(choices=[('libros', 'Libros'), ('electronica', 'Electrónica'), ('ropa', 'Ropa'), ('otros', 'Otros')], max_length=20)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
            ],
        ),
    ]
