# Generated by Django 5.2.4 on 2025-07-13 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vender', '0002_producto_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='publicado',
            field=models.BooleanField(default=False),
        ),
    ]
