# Generated by Django 5.2.4 on 2025-07-13 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vender', '0003_producto_publicado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('libros', 'Libros'), ('electrónica', 'Electrónica'), ('ropa', 'Ropa'), ('otros', 'Otros')], max_length=20),
        ),
    ]
